JuliaMath/QuadGK.jl

README.md
docs/src/index.md
src/QuadGK.jl

I'll put all of the requested changes into this PR so that it can be tagged once this is merged.
Fixes #1

Incorporate Steven's comments

---

.travis.yml
REQUIRE
test/REQUIRE
test/runtests.jl

Apparently there is at least one package that wants to depend on QuadGK.jl and still maintain support for 0.4, and since Julia-version-conditional package dependencies isn't a thing at the moment, this is easier and preferable to conditionally calling Pkg.add (which breaks tracking of what was installed because the user asked for it, vs as a dependency).

Enable support for Julia 0.4

---

.travis.yml
src/QuadGK.jl

Fixes #8, e.g. on julia 0.6:
```
julia-0.6> using QuadGK
julia-0.6> quadgk(sin, 0, 1)
(0.4596976941318603, 5.551115123125783e-17)
```
On julia 0.4 and 0.5, the same code will use the version from `Base`, unless calls to `quadgk` are qualified explicitly.
This should ensure a smooth transition.
I used [this commit](https://github.com/JuliaLang/julia/commit/dbbd7e510d54810071d81acfd849e657bbb36dbd) for computing the julia version.
This also adds julia 0.6 to the Travis tests.

Override quadgk deprecation in Base

---

src/QuadGK.jl

Running tests shows another warning:
```
┌ Warning: `scale!(A::AbstractArray, b::Number)` is deprecated, use `mul1!(A, b)` instead.
│   caller = eigvec1(::Array{BigFloat,1}, ::BigFloat, ::Int64) at QuadGK.jl:322
└ @ QuadGK QuadGK.jl:322
```
but doesn't look like `Compat` supports `mul1!`.

Load LinearAlgebra standard library

---

.travis.yml
REQUIRE
src/QuadGK.jl
test/runtests.jl

This package hasn't changed in a while, and since https://github.com/JuliaLang/Compat.jl/commit/f5e14bd5f9b8d69209282759c1699a8eea60a826 hasn't been tagged in a Compat.jl release yet it was easier to just drop 0.6 support on `master`.

bump to require 0.7

---

src/QuadGK.jl
test/runtests.jl

I just realized that we should probably use the same names as `Base.isapprox` for these keywords.
Requires a major version bump since it changes the API.  I'll make a corresponding PR for the 0.6 branch so that code that needs 0.6 compatibility can use the new API also.

use rtol/atol instead of reltol/abstol, like Base.isapprox

---

src/QuadGK.jl
test/runtests.jl

I was using a function that is implemented only for `Float32`, but using QuadGK it ends up being evaluated with a `Float64` argument.
A working example (on Julia 1.0.1):
```jl
julia> using QuadGK
julia> cos32(x::Float32) = cos(20x)
cos32 (generic function with 1 method)
julia> quadgk(cos32, 0f0, 1f0)
ERROR: MethodError: no method matching cos32(::Float64)
Closest candidates are:
cos32(::Float32) at REPL[8]:1
Stacktrace:
[1] evalrule(::typeof(cos32), ::Float32, ::Float64, ::Array{Float32,1}, ::Array{Float32,1}, ::Array{Float32,1}, ::typeof(LinearAlgebra.norm)) at /Users/daan/.julia/packages/QuadGK/fTRFu/src/QuadGK.jl:59
[2] do_quadgk(::typeof(cos32), ::Array{Float32,1}, ::Int64, ::Type{Float32}, ::Float32, ::Float32, ::Int64, ::typeof(LinearAlgebra.norm)) at …
```

Do not accidentally convert numeric type to Float64

---

.gitignore
.travis.yml
Project.toml
REQUIRE
test/runtests.jl

In Julia 1.2, `norm` calls `float` see https://github.com/JuliaLang/julia/pull/30481

Updates for Julia 1.2

---

src/adapt.jl
src/evalrule.jl
src/gausskronrod.jl
test/runtests.jl

Makes the `quadgk` function type-stable.  Closes #21. Closes #19. Closes #15.  Closes #20.
Also fixes handling of some other other number types, and in particular fixes dimensionful types (#17).  Mostly supersedes https://github.com/PainterQubits/UnitfulIntegration.jl, cc @ajkeller34:
```jl
julia> using Unitful, QuadGK, Test
julia> @inferred quadgk(x -> x^2, 0u"m", 1u"m")
(0.3333333333333333 m^3, 5.551115123125783e-17 m^3)
```
It still doesn't completely address #13, because it only works if `real(one(T))` returns the underlying real numeric type for computing the quadrature weights etc.   This doesn't work for dual numbers (ForwardDiff.jl) or measurements (JuliaPhysics/Measurements.jl#31), and in general I haven't been able to think of a way to do this that works across packages.

type stability

---

Project.toml

`QuadGK` holds package `DataStrctures` to `v0.15`, which is incompatible with requirement for new versions of `DifferentialEquations` (and maybe some other packages). It seems to be OK to add `v0.17` to the compatible list. The tests still pass. 
This is related to #39.

Add 0.17 as a compatible version for DataStructures

---

README.md
src/QuadGK.jl
src/adapt.jl
src/evalrule.jl
test/runtests.jl

Closes #12.
@ChrisRackauckas, this cuts down on the allocations by a factor of 3–10 for array-valued integrands.  Is that what you had in mind?
There's more code duplication than I would ideally like, but it isn't too bad.

quadgk! function for more in-place operation on array-valued integrands

---

src/gausskronrod.jl

The previous behavior led to https://discourse.julialang.org/t/error-with-forwarddiff-in-turing/88633/16 . Dual numbers would just hit an infinite recursion because `float(::Dual)::Dual !<: AbstractFloat`. This should handle more cases where float(T) !<: AbstractFloat too, like TrackedReal.
Though I know that this probably isn't the best way to handle it. In a higher level interface like Integrals.jl, I think it would be better to detect such differentiation by boundary terms and specialize it. It's actually kind of funny and would be a good homework problem. If you put a dual number into the boundary with dual part one, i.e. , so then you integrate (f + df/dt eps) dt and by linearity of the integral it's just fundamental theorem of calculus approximated by GK! However, the argument above …

Duals in the boundary values: avoid infinite recursion

---

src/adapt.jl
test/runtests.jl

Fixes #50 
```julia
using QuadGK
using BenchmarkTools
using Test
f(x) = 1 / x^2
g(x) = [f(x)]
f!(y, x) = y .= f(x)
@btime quadgk($f, 1., 100.)          # 1.187 μs (2 allocations: 368 bytes)
@btime quadgk($g, 1., 100.)          # 27.081 μs (728 allocations: 45.73 KiB)
@btime quadgk!($f!, [0.], 1., 100.)  # 4.218 μs (39 allocations: 2.67 KiB)
@btime quadgk($f, 1., Inf)           # 135.747 ns (0 allocations: 0 bytes)
@btime quadgk($g, 1., Inf)           # 2.906 μs (77 allocations: 4.81 KiB)
@btime quadgk!($f!, [0.], 1., Inf)   # 729.695 ns (14 allocations: 896 bytes)
```

Inplace method with Inf domain

---

src/adapt.jl
test/runtests.jl

handle unitful infinite arguments

---

docs/src/functions.md
docs/src/index.md
docs/src/quadgk-examples.md
src/QuadGK.jl
src/adapt.jl
test/runtests.jl

Greatly expanded the documentation with many examples.  (Closes #44.)
Also adds two convenience functions `quadgk_count` and `quadgk_print` which wrap `quadgk` and count and/or print the integrand evaluations, respectively.

add tutorial examples, and quadgk_count and quadgk_print

---

.github/workflows/CI.yml
.github/workflows/TagBot.yml
.github/workflows/documentation.yml
Project.toml

It looks like the documentation is no longer being built — when @timholy switched to Github CI (#51) from Travis, did we forget to port over the doc building from Travis?
Also, while I'm updating these scripts, we can drop our ancient support for Julia 0.7, which no one cares about anymore.  Also updated the TagBot script to the latest recommended script since we had to add the DOCUMENTER_KEY to that anyway.

add doc-build action

---

src/gausskronrod.jl

Just a slightly narrower type in the internal rule cache.

ensure int keys in rulecache

---

src/batch.jl
test/runtests.jl

handle integrands <: AbstractVector

---

src/adapt.jl
src/batch.jl
src/evalrule.jl
test/runtests.jl

This pr concerns issues #86, #82, and #39, and addresses errors arising from evaluation of the integrand at the endpoints of the interval. This pr handles the endpoints by:
* throwing a `DomainError` if the roundoff happens on an initial segment
* silently returning the best integral and error estimate if the roundoff happens during refinement
I think it would be better to warn the user of the following situations in which `quadgk` silently returns a possibly unconverged result
* endpoint roundoff error
* maxevals reached
Should we do this and add return codes?

avoid integrand evaluations at endpoints

---

src/adapt.jl
src/batch.jl
test/runtests.jl

Fixes https://github.com/JuliaMath/QuadGK.jl/issues/97#issuecomment-1888256879
Basically, if the user passes an initial interval that is so small that the quadrature points round to one of the endpoints, it has to be allowed — it causes too much trouble to try to forbid this.

allow endpoints evaluation for tiny initial intervals

---

docs/src/gauss-kronrod.md
docs/src/index.md
docs/src/quadgk-examples.md
docs/src/weighted-gauss.md
src/QuadGK.jl
src/gausskronrod.jl

Add language tags `julia` and `julia-repl` for Documenter.jl to pick up and highlight in deployed documentation website.

Add language tags to code samples

---

docs/src/gauss-kronrod.md
docs/src/weighted-gauss.md
src/adapt.jl
src/batch.jl
src/evalrule.jl
src/gausskronrod.jl
test/runtests.jl

In some places we wrote the Gauss weights as `wg`, and in others as `gw`.  This PR changes the code and docs to use `wg` consistently.
(Not breaking.)
Fixes #106.

rename gw -> wg

---

src/gausskronrod.jl

Since Newton iterations should be quadratically converging by the time we approach machine precision, the final iteration here is pointless (the next correction should be of order $\varepsilon^2$).

omit pointless extra Newton iteration for λ

---

src/gausskronrod.jl

For symmetric rules (corresponding to a `HollowSymTridiagonal` Jacobi matrix), we can speed up `gauss` by only doing Newton refinement and eigenvector calculation for half of the points, since the other half are the mirror image.
This gives a 2x speedup for `BigFloat` gauss rules, where these steps dominate.  It doesn't seem to make much difference for `Float64` gauss rules, which are probably dominated by the LAPACK `eigvals` call.

speedup gauss for symmetric rules

---

.github/workflows/CI.yml
Project.toml
test/runtests.jl

This adds the new weakdep Enzyme to the "extras" section and for testing.
Also adds a compat entry for the stdlib LinearAlgebra since [that is required nowadays](https://discourse.julialang.org/t/psa-compat-requirements-in-the-general-registry-are-changing/104958).
bumps the Julia version requirement to 1.6 since that is needed by Enzyme (a test dependency even though it is optional for installation), and it is a pain to continue to support 1.2 with this dependency present.  Not much point in supporting ancient Julia versions these days.

add Enzyme to "extras" for testing, docs

---

src/gausskronrod.jl

Make `quadgk` calls thread-safe, by putting a lock around access to the rule-cache dictionaries.  From https://github.com/JuliaMath/HCubature.jl/issues/69

make quadgk thread-safe

---

src/evalrule.jl

Was perusing the code and noticed a missing dot resulting in an unnecessary intermediate allocation. Also changed these three lines to use the already unpacked names `fg,fk` rather than access them as properties of `f`.

Fix in-place broadcast fusion in evalrule

---

test/runtests.jl

due to `SymTridiagonal` throwing a different exception type

fix test for Julia 1.11

---

src/adapt.jl

I ran into this issue when running `quadgk` using the `ArbReal` type from `ArbNumerics.jl`:
```julia
julia> using QuadGK, ArbNumerics
julia> quadgk(x->exp(-x^2/2), ArbReal.((0, Inf))...; rtol = 1e-30)
ERROR: DomainError with nan:
integrand produced nan in the interval (nan, 1.0)
Stacktrace:
[1] evalrule(f::QuadGK.var"#188#197"{…}, a::ArbReal{…}, b::ArbReal{…}, x::Vector{…}, w::Vector{…}, wg::Vector{…}, nrm::typeof(norm))
@ QuadGK ~/.julia/dev/QuadGK/src/evalrule.jl:39
[2] #8
@ ~/.julia/dev/QuadGK/src/adapt.jl:54 [inlined]
[3] ntuple
@ ./ntuple.jl:48 [inlined]
[4] do_quadgk(f::QuadGK.var"#188#197"{…}, s::Tuple{…}, n::Int64, atol::Nothing, rtol::Float64, maxevals::Int64, nrm::typeof(norm), _segbuf::Nothing, eval_segbuf::Nothing)
@ QuadGK ~/.julia/dev/QuadGK/src/adapt.jl:52
[5] #50
@ …
```

Match half-infinite interval endpoint handling behaviour with infinite interval
